Freetz/freetz

- make/mc/Config.in
- make/mc/mc.mk
> Update Midnight Commander from version 4.8.21 to 4.8.22

- FIRMWARES
- config/mod/download.in
Update for the Fritz!Box 7590 Labor 07.08-65777
> FB 7590 Labor 07.08-65777

- FIRMWARES
- config/mod/download.in
Adds the FritzBox 7590 Labor 07.08-66527 version
> FB 7590 Labor 07.08-66527 Update

- FIRMWARES
- config/mod/download.in
Adds the newest labor versions for the FB 7490 and 7590
Versions: 07.08 rev66900 for the 7490 and 07.08 rev66902 for the 7590
> FB7490: 07.08 rev66900 Labor & FB7590: 07.08 rev66902 Labor Update

- CHANGELOG
- make/tor/Config.in
- make/tor/patches/010-drop_backtrace_support.patch
- make/tor/tor.mk
version bump and path fix for compiled binary
> tor: bump to version 0.3.5.8; runtime tested

- FIRMWARES
- config/ui/firmware.in
because compiling and running tested, escpecially labor
> 6890: drop EXPERIMENTAL status

- CHANGELOG
- make/vim/Config.in
- make/vim/patches/100-dont_check_for_libelf.patch
- make/vim/vim.mk
> vim: bump to 8.1.1491

- FIRMWARES
- config/mod/download.in
> 4040,7520,7530: bump firmware to FOS 7.12

- CHANGELOG
- make/tor/Config.in
- make/tor/tor.mk
> Tor bump -> 0.4.0.5

- make/getdns/files/.language
- make/getdns/files/root/etc/default.getdns/getdns.cfg
- make/getdns/files/root/etc/default.getdns/getdns.def
- make/getdns/files/root/etc/default.getdns/getdns_conf
- make/getdns/files/root/etc/default.getdns/getdns_conf.def
- make/getdns/files/root/etc/init.d/rc.getdns
- make/getdns/files/root/usr/lib/cgi-bin/getdns.cgi
Mein erstes webui in freetz, habe mich an anderen Paketen orientiert.
> stubby webui

- CHANGELOG
- make/haproxy/Config.in
- make/haproxy/haproxy.mk
- make/haproxy/patches/010-disable_epoll_for_kernel_smaller_2.6.28.patch
http://www.haproxy.org/download/1.8/src/CHANGELOG
> HAProxy bump -> 1.8.21.

- FIRMWARES
- config/mod/download.in
compile-tested
hardware-tested
> 3370: bump Fritz!OS 6.5x version to 06.55 rev38670

- make/tor/files/root/etc/init.d/rc.tor
tested with and without countrycodes
> tor: fixed geoip-download

- tools/make/mklibs/mklibs.mk
> mklibs: fix download site url

- CHANGELOG
- make/openvpn/Config.in
- make/openvpn/openvpn.mk
OpenVPN bump -> OpenVPN 2.4.8
Changelog: https://community.openvpn.net/openvpn/wiki/ChangesInOpenvpn24
Fixes https://github.com/Freetz/freetz/issues/235
> OpenVPN version bump -> OpenVPN 2.4.8

- CHANGELOG
- make/haproxy/Config.in
- make/haproxy/haproxy.mk
http://www.haproxy.org/download/1.8/src/CHANGELOG
> haproxy bump -> 1.8.23

- FIRMWARES
- config/mod/download.in
> 6820/6890: bump to Fritz!OS 7.13

- make/busybox/Config.in
`root@fritz.box# ip -6 neigh`
`fe80::95a2:cc2:8ce0:8c39 dev ens192 lladdr 00:0c:29:11:22:33 STALE`
`fe80::20c:29ff:fe45:6462 dev ens192 lladdr 00:0c:29:11:22:33 STALE`
`fe80::20c:29ff:feed:9d02 dev ens192 lladdr 00:0c:29:11:22:33 STALE`
> Add neighbor support to ip command.

- CHANGELOG
- make/curl/Config.in
- make/curl/curl.mk
- make/curl/patches/130-CPPFLAGS_as_CFLAGS.patch
Changelog: https://curl.haxx.se/changes.html#7_69_1
> curl: bump version to 7.69.1

- make/mc/patches/040-provide-O_CLOEXEC.patch
see  https://midnight-commander.org/ticket/4052
> Fix compilation of Midnight Commander on FB 7112

- make/wireguard/wireguard.mk
corrected sha256 checksum for wireguard package: 1.0.20200319
> correction of sha256 checksum

- CHANGELOG
- make/curl/Config.in
- make/curl/curl.mk
- make/curl/patches/100-makefile_no_docs.patch
- make/curl/patches/101-cross_compile_writable_argv.patch
- make/curl/patches/102-binary_static.patch
- make/curl/patches/103-no_manual_compile_fix.patch
- make/curl/patches/110-gnu_source__reentrant.patch
- make/curl/patches/130-CPPFLAGS_as_CFLAGS.patch
CHANGELOG: https://curl.haxx.se/changes.html#7_70_0
> curl: bump version to 7.70.0

- CHANGELOG
- make/openvpn/Config.in
- make/openvpn/openvpn.mk
- make/openvpn/patches/2.4/100-tun-tcp-inetd-nowait.patch
- make/openvpn/patches/2.4/110-omit_configure_params.patch
- make/openvpn/patches/2.4/210-disable_epoll_poll_use_select.patch
- make/openvpn/patches/2.4/230-fix_missing_u64.patch
- make/openvpn/patches/2.4/obfuscation/300-xor_scramble.patch
CHANGELOG:  
https://github.com/OpenVPN/openvpn/blob/release/2.4/Changes.rst#version-249
> openvpn: bump version to 2.4.9

- Makefile
- README
update some URI from the old wiki location to point to freetz.github.io instead
> update some URI

- CHANGELOG
- make/curl/Config.in
- make/curl/curl.mk
Changelog: https://curl.haxx.se/changes.html#7_71_1
> curl: bump version to 7.71.1

- CHANGELOG
- config/ui/fwmod.in
- config/ui/patches.in
- fwmod
- make/phonebook-tools/files/root/usr/bin/phonebook-tools
- tools/unpack-kernel
stop-gap measure to improve documentation at least somewhat
> replace AWOL wehavemorefun.de links with archive.org backups

- CHANGELOG
- make/dnsmasq/Config.in
- make/dnsmasq/dnsmasq.mk
- make/dnsmasq/patches/030-support_dnssec_timestamp_on_readonly_fs.patch
- make/dnsmasq/patches/040-dnssec_signature_timestamp_startup_state.patch
Changelog: http://www.thekelleys.org.uk/dnsmasq/CHANGELOG
> dnsmasq: bump version to 2.82

- CHANGELOG
- make/dropbear/Config.in
- make/dropbear/dropbear.mk
Changelog: https://matt.ucc.asn.au/dropbear/CHANGES
> dropbear: bump version to 2020.81

- CHANGELOG
- make/stunnel/Config.in
- make/stunnel/stunnel.mk
CHANGELOG: https://www.stunnel.org/NEWS.html
> stunnel: bump version to 5.57

- CHANGELOG
- make/dnsmasq/Config.in
- make/dnsmasq/dnsmasq.mk
Changelog: http://www.thekelleys.org.uk/dnsmasq/CHANGELOG
> dnsmsaq: bump version to 2.83
