patches/scripts/500-remove_mediasrv.sh

see this IPPF thread:
https://www.ip-phone-forum.de/threads/7390-06-85-14948-mediaserver.302469/
According to https://github.com/Freetz/freetz/blob/master/config/avm/features.in#L180
only very old 7270v1 versions had a plugin-based media server.
Removing the menu entry for this feature makes only sense, if the user explicitly
gave this order (via FREETZ_REMOVE_MEDIASRV - handled in line 1 of patch script) or
if he wants to integrate plugins and refuses to do this for the mediaserver plugin
(handled in line 2 and defined here:
https://github.com/Freetz/freetz/blob/master/config/ui/avm-plugins.in#L15).
Due to the used reverse logic (a met condition stops the script), the missing
~FREETZ_AVM_HAS_PLUGIN_MEDIASRV~ FREETZ_AVMPLUGINS_MEDIASRV symbol fulfills the "not equal 'y'" condition for …

remove_mediasrv: fix patch file for 7390 devices

---

make/sqlite/patches/900-no_speed_optimizations.patch

Overrule any existing '-Ofast' flag with '-O2' - SQLite 3 will not compile with '-ffast-math' set, which is part of speed optimizations. Look at line 29485 in sqlite.c for further info.
This patch is usually not needed by many Freetz users, because "size optimization" is still the preferred (and default) style. But if a Freetz user sets the `-Ofast` option himself, `sqlite3` compilation fails without some countermeasures - this patch is **one** possible solution.

sqlite3: ignore optimizations for speed

---

make/inetd/files/root/bin/inetdctl
make/mod/files/root/etc/init.d/rc.ftpd
make/mod/files/root/etc/init.d/rc.mod
make/mod/files/root/etc/init.d/rc.smbd

smbd und ftpd werden bei schon beim Booten angeschlossenen Speichermedien nicht in die inetd.conf eingetragen

Racecondition (udev vs. rc.mod) beheben (#2908)

---

patches/scripts/115-patch-ds_off.sh

Starting with (at least) FRITZ!OS 7, the former file '/etc/init.d/S99-tail'
has been renamed as '/etc/init.d/E99-tail'.
As a result, the init script for Freetz's own modifications (rc.mod) is
not longer started AFTER the watchdog was terminated in
'/etc/init.d/rc.tail.sh', because 'S99-zzz-rcmod' gets executed first
and '/etc/init.d/E99-tail' (which includes 'rc.tail.sh') will not run,
until 'S99-zzz-rcmod' (which calls in turn 'rc.custom', if it exists)
was finished.
Depending on the duration of actions needed to initialize Freetz packages,
the bootup watchdog may get triggered, before it's deactivated in
'/etc/init.d/rc.tail.sh'.
The watchdog timeout from "init-start" is model-dependent - usually 120 or
240 seconds are used. If the original firmware sets the WDT to 120 seconds,
it's …

rc.mod: restore the order of execution at startup

---

make/ltrace/patches/900-uninitialized.patch

Wegen eines "fall-through" in einem "switch"-Statement erkennt der Optimizer des C-Compilers hier eine möglicherweise nicht initialisierte Variable "nrhs", wenn man mit den Freetz-Vorgaben (-Wall, -Werror) kompiliert:
```
/bin/sh ./libtool  --tag=CC   --mode=compile /home/freetz/vr9_07.01_speed/toolchain/build/mips_gcc-5.5.0_uClibc-1.0.14-nptl_kernel-3.10/mips-linux-uclibc/bin/mips-linux-uclibc-gcc -DHAVE_CONFIG_H -I.  -DSYSCONFDIR=\"/etc\"  -DPKGDATADIR=\"/usr/share/ltrace\"    -I/home/freetz/vr9_07.01_speed/toolchain/build/mips_gcc-5.5.0_uClibc-1.0.14-nptl_kernel-3.10/mips-linux-uclibc/usr/include     -I./sysdeps/linux-gnu/mips      -I./sysdeps/linux-gnu   -I./sysdeps     -I.   -Wall -Wsign-compare -Wfloat-equal -Wformat-security -Werror -march=34kc -mtune=34kc -msoft-float -Ofast -pipe …
```

ltrace: silence a warning due to a fall-through in a switch statement

---

make/busybox/Config.in.busybox
make/busybox/generate.sh
toolchain/make/target/uclibc/0.9.33.2/999-setns.upstream.patch

siehe IPPF-Thread:
https://www.ip-phone-forum.de/threads/busybox-1-27-2-neue-applets-bringen-neue-abh%C3%A4ngigkeiten-von-der-kernel-version.298282/
Über die Notwendigkeit von Namespaces auf der FRITZ!Box bestand keine Einigkeit, wie man im oben verlinkten Thread nachlesen kann.
Da es inzwischen eine "reale Anwendung" solcher Namespaces auf einer FRITZ!Box gibt (https://www.ip-phone-forum.de/threads/lost-in-translation-oder-wie-man-doch-noch-zu-einer-verst%C3%A4ndlichen-lua-seite-bei-avm-kommt.301428/ bzw. https://github.com/PeterPawn/YourFritz/blob/master/tools/get_page), mache ich aus dem Backport von "setns(I)" auf die uClibc 0.9.33 nun doch noch mal einen PR ... ein Gerät, was mit einem Kernel > 3.0 und der uClibc-0.9.33.2 arbeitet (und das vermutlich noch lange muß), wäre z.B. die …

busybox + uclibc-target: add setns() function and related applets

---

make/linux/patches/2.6.39.3.x86/989-no-error-unused-parameter.patch

This pull request is adding a patch for drivers/net/avm_cpu_connect/Makefile which adds the parameter "-Wno-error-unused-parameter" to fix a compile error #147.

Adding a patch to fix issue #147.

---

FIRMWARES
config/mod/download.in

Update to newest versions:
4040: 155.07.08 rev67481
6890 LTE: 162.07.08 rev67492
7530: 164.07.08 rev67480

Labor version bump for 4040/6890 LTE/7530

---

make/dnsmasq/files/root/etc/default.dnsmasq/dnsmasq_conf

When DNSSEC is enabled, disable its time checks until NTP set the
system time properly. Reuse /etc/version as reference file.
Closes #163

dnsmasq: Avoid problems with DNSSEC after reboot

---

CHANGELOG
make/bind/bind.mk
make/bind/files/root/etc/init.d/rc.bind
make/bind/patches/020-isc_atomic_xadd.patch

* bump version to 9.11.6-P1
* included patch from https://gitlab.isc.org/isc-projects/bind9/commit/ef49780d30d3ddc5735cfc32561b678a634fa72f
to fix compilation problem with uClibc
* fixed bug in rc.bind (stop() called by modlib_stop(), resulting in doubly attempted kill for 'named' process)
* removed obsolete stuff from bind.mk

 bind: version bump to 9.11.6-P1 and fixes

---

patches/scripts/800-modfs_boot_manager.sh
tools/make/yourfritz-host/yourfritz-host.mk

Das ist **mein** Vorschlag zur vorläufigen/unmittelbaren Korrektur von #115 bei der Verwendung des Patch-Skripts im Rahmen von "fwmod_custom" bzw. bei anderen Aufrufen, wo die erforderlichen Variablen nicht gesetzt sind. Wenn jemand eine andere (oder gar bessere, wobei mich da dann wieder der "Bewertungsmaßstab" interessieren würde) Lösung hat, geht das für mich auch in Ordnung, solange daraus keine Forderungen für weitere Änderungen im YourFritz-Repo resultieren, die dann nur dazu dienen, diese andere Implementierung irgendwie möglich zu machen - so etwas bräuchte dann schon eine deutlich plausible Begründung.
Ich weiche hier doch noch einmal von meiner generell geänderten Haltung (bzgl. PRs von mir) ab, da es sich um eine Korrektur für einen früheren, inzwischen irgendwie auch …

patches: modfs boot manager installation

---

CHANGELOG
make/haproxy/Config.in
make/haproxy/haproxy.mk

changelog: http://git.haproxy.org/?p=haproxy-1.8.git;a=log;h=refs/tags/v1.8.22

haproxy version bump -> haproxy 1.8.22

---

CHANGELOG
make/tor/Config.in
make/tor/tor.mk

Changelog: 
https://gitweb.torproject.org/tor.git/tree/ChangeLog?h=tor-0.4.2.5&id=bede4ea1008920d8b1b9ea72b0f44cb2ea4dbc6b

Tor version bump -> 0.4.2.5

---

make/mod/files/root/usr/bin/modhosts

IP field can only be IPv4 or IPv6. 
Tested with dnsmasq to resolv AAAA from /etc/hosts.
This fixes https://github.com/Freetz/freetz/issues/74

Adding IPv6 to /etc/hosts when defined in freetz hosts config.

---

CHANGELOG
make/haproxy/Config.in
make/haproxy/haproxy.mk

Changelog: http://www.haproxy.org/download/1.8/src/CHANGELOG

haproxy version bump -> 1.8.24

---

CHANGELOG
make/tor/Config.in
make/tor/tor.mk

Changelog: https://gitweb.torproject.org/tor.git/plain/ChangeLog?h=tor-0.4.2.6

Tor version bump -> 0.4.2.6

---

CHANGELOG
make/tor/Config.in
make/tor/tor.mk

Changelog:
https://gitweb.torproject.org/tor.git/plain/ChangeLog?h=tor-0.4.2.7

tor: bump version to 0.4.2.7

---

CHANGELOG
make/haproxy/Config.in
make/haproxy/haproxy.mk
make/haproxy/patches/010-disable_epoll_for_kernel_smaller_2.6.28.patch

Changelog: http://www.haproxy.org/download/1.8/src/CHANGELOG

haproxy: bump version to 1.8.25

---

Makefile

Quick fix (first idea) to avoid password compromise while adding `.config.compressed` to any error reports. It does not cover the *original* `.config` file, if a user adds this one to his report.
A much better solution would (imho) be a "collect-diagnose-data" script, which uses the existing `fmake` script to produce a detailed log file of the error case and puts this log, together with the compressed and cleaned-up configuration file, into one single ZIP file, which may be uploaded/added by the reporting user.

Makefile: remove key password from .config.compressed

---

tools/make/squashfs2-host/patches/910-gcc10_fix_multiple_definitions_error.patch
tools/make/squashfs3-host/patches/910-gcc10_fix_multiple_definitions_error.patch
tools/make/squashfs4-host-be/patches/910-gcc10_fix_multiple_definitions_error.patch

gcc-10 and above flipped a default from -fcommon to -fno-common. For more details see [https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common](https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common). These patches are changing the source (the prefered method mentioned in the gentoo wiki) to fix the problem.

squashfs*-tools and gcc10

---

make/linux/patches/2.6.39.3.x86/220-fix_gcc10_dtc.patch

related to
https://git.kernel.org/pub/scm/utils/dtc/dtc.git/patch/?id=0e9225eb0dfec51def612b928d2f1836b092bc7e

Fix kernel 2.6.39 host tools compilation with gcc 10

---

CHANGELOG
make/tor/Config.in
make/tor/patches/010-drop_backtrace_support.patch
make/tor/tor.mk

CHANGELOG: 
https://gitweb.torproject.org/tor.git/plain/ChangeLog?h=tor-0.4.3.5

tor: bump version to 0.4.3.5

---

.build-prerequisites

The file 'kernel/timeconst.h' is generated from a 'bc' program, see
'kernel/timeconst.bc' for details.

.build-prerequisites: 'bc' is needed for newer kernel sources, too

---

CHANGELOG
make/haproxy/Config.in
make/haproxy/haproxy.mk

Changelog: https://www.haproxy.org/download/1.8/src/CHANGELOG

haproxy: bump version to 1.8.26

---

CHANGELOG
make/tor/Config.in
make/tor/tor.mk

Changelog: 
https://gitweb.torproject.org/tor.git/plain/ChangeLog?h=tor-0.4.3.6

tor: bump version to 0.4.3.6

---

CHANGELOG
make/wireguard-linux-compat/Config.in
make/wireguard-linux-compat/wireguard-linux-compat.mk
make/wireguard/Config.in
make/wireguard/wireguard.mk

- wireguard-tools-1.0.20200820
- wireguard-linux-compat-1.0.20200729
Changelog:
- https://git.zx2c4.com/wireguard-tools/log/?h=v1.0.20200820
- https://git.zx2c4.com/wireguard-linux-compat/log/?h=v1.0.20200729

wireguard: bump version

---

CHANGELOG
make/tor/Config.in
make/tor/patches/010-drop_backtrace_support.patch
make/tor/tor.mk

Changelog: 
https://gitweb.torproject.org/tor.git/plain/ChangeLog?h=tor-0.4.4.5

Tor: bump version to 0.4.4.5

---

CHANGELOG
make/haproxy/Config.in
make/haproxy/haproxy.mk

CHANGELOG: https://www.haproxy.org/download/1.8/src/CHANGELOG

haproxy: bump version to 1.8.27

---

CHANGELOG
make/tor/Config.in
make/tor/tor.mk

Changelog:
https://gitweb.torproject.org/tor.git/plain/ChangeLog?h=tor-0.4.4.6

tor: bump version to 0.4.4.6

---

CHANGELOG
make/dnsmasq/Config.in
make/dnsmasq/dnsmasq.mk

Changes: http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=summary
Ist nur ein RC, aber löst erstmal das Problem mit dem loggen von "failed to send packet: Network is unreachable"
Sobald 2.84 released wurde, erstelle ich einen neuen PR.

dnsmasq: bump version to 2.84rc2

---

CHANGELOG
make/cacerts/Config.in
make/cacerts/cacerts.mk

Mozilla extract from curl https://curl.se/docs/caextract.html

cacerts: bump version to 2021-01-19

---

CHANGELOG
make/haproxy/Config.in
make/haproxy/haproxy.mk

CHANGELOG: http://www.haproxy.org/download/1.8/src/CHANGELOG

haproxy: bump to v 1.8.28
